name = "forth"
entrypoint = "main.fs"
extensions = [
  "fs"
]
packages = [
  "gforth"
]
setup = [ ]

[run]
pty = true
command = [
  "gforth",
  "--",
  "./main.fs",
  "-e",
  "bye"
]

[tests]

  [tests.hello]
  code = ".\" hello\" CR"
  output = "hello\n"