name = "objective-c"
entrypoint = "main.m"
extensions = [
  "m"
]
packages = [
  "gobjc",
  "gnustep",
  "gnustep-devel"
]

setup = [
  ". /usr/share/GNUstep/Makefiles/GNUstep.sh"
]

[compile]
command = [
  "gcc",
  "-o",
  "main",
  "main.m",
  "-I/usr/include/GNUstep",
  "-L/usr/lib/GNUstep",
  "-lobjc",
  "-lgnustep-base"
]

[run]
pty = true
command = [
  "/home/runner/main"
]

[tests]

  [tests.hello]
  code = "#import <Foundation/Foundation.h>\nint main(void) {\n\tNSAutoreleasePool *pool = [NSAutoreleasePool new];\n\tputs(\"hi\");\n\t[pool drain];\n\treturn 0;\n}"
  output = "hi\n"
