name = "rust"
entrypoint = "main.rs"
extensions = [
  "rs"
]
packages = [
  "rustc",
  "cargo",
  "rust-gdb"
]

[compile]
command = [
  "rustc",
  "-o",
  "main"
]

[run]
command = [
  "./main"
]

[tests]

  [tests.hello]
  code = "fn main() {\n  println!(\"hello\");\n}"
  output = "hello\n"
